name: Run pytest

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: {python-version: 3.8}
      - id: cachevenv
        uses: actions/cache@v2
        with:
          path: venv
          key:          ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-venv-
      - run: python -m venv venv
        if: '!steps.cachevenv.outputs.cache-hit'
      - run: venv/bin/pip install -r requirements.txt
        if: '!steps.cachevenv.outputs.cache-hit'
      - run: venv/bin/pytest -v
